version: '3'

tasks: 
  generate:
    aliases:
      - gen
    description: "generate go files using protobuf contract by path ./proto"
    cmds:
      - protoc -I proto ./proto/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative

  default:
    cmds: [task gen]